var collection = [


	

		{
			"kind": "peeing",
			"duration": 1.12,
			"img": ".../sdfs.jpg",
			"daynumber": 1,
			"day": "tue",
		},
		{
			"kind": "pooping",
			"duration": 12.29,
			"img": ".../sdfs.jpg",
			"daynumber": 1,
			"day": "tue",
		},
		{
			"kind": "peeing",
			"duration": 1.11,
			"img": ".../sdfs.jpg",
			"daynumber": 2,
			"day": "wed",
		},
		{
			"kind": "pooping",
			"duration": 9.57,
			"img": ".../sdfs.jpg",
			"daynumber": 2,
			"day": "wed",
		},	 
		{
			"kind": "peeing",
			"duration": 0.51,
			"img": ".../sdfs.jpg",
			"daynumber": 3,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 0.11,
			"img": ".../sdfs.jpg",
			"daynumber": 3,
			"day": "thu",
		},
		{
			"kind": "pooping",
			"duration": 25.12,
			"img": ".../sdfs.jpg",
			"daynumber": 3,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 1.02,
			"img": ".../sdfs.jpg",
			"daynumber": 4,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 0.46,
			"img": ".../sdfs.jpg",
			"daynumber": 4,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 1.01,
			"img": ".../sdfs.jpg",
			"daynumber": 4,
			"day": "fri",
		},
		{
			"kind": "pooping",
			"duration": 26.28,
			"img": ".../sdfs.jpg",
			"daynumber": 4,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 0.56,
			"img": ".../sdfs.jpg",
			"daynumber": 5,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 0.48,
			"img": ".../sdfs.jpg",
			"daynumber": 5,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 0.35,
			"img": ".../sdfs.jpg",
			"daynumber": 6,
			"day": "sun",
		},
		{
			"kind": "pooping",
			"duration": 13.44,
			"img": ".../sdfs.jpg",
			"daynumber": 6,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 1.05,
			"img": ".../sdfs.jpg",
			"daynumber": 6,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.41,
			"img": ".../sdfs.jpg",
			"daynumber": 7,
			"day": "mon",
		},
		{
			"kind": "pooping",
			"duration": 18.56,
			"img": ".../sdfs.jpg",
			"daynumber": 7,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.45,
			"img": ".../sdfs.jpg",
			"daynumber": 7,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.44,
			"img": ".../sdfs.jpg",
			"daynumber": 8,
			"day": "tue",
		},
		{
			"kind": "pooping",
			"duration": 30.00,
			"img": ".../sdfs.jpg",
			"daynumber": 8,
			"day": "tue",
		},
		{
			"kind": "peeing",
			"duration": 0.35,
			"img": ".../sdfs.jpg",
			"daynumber": 9,
			"day": "wed",
		},
		{
			"kind": "peeing",
			"duration": 1.07,
			"img": ".../sdfs.jpg",
			"daynumber": 10,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 0.51,
			"img": ".../sdfs.jpg",
			"daynumber": 10,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 1.05,
			"img": ".../sdfs.jpg",
			"daynumber": 11,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 0.53,
			"img": ".../sdfs.jpg",
			"daynumber": 11,
			"day": "fri",
		},
		{
			"kind": "pooping",
			"duration": 13.56,
			"img": ".../sdfs.jpg",
			"daynumber": 11,
			"day": "fri",
		},
		{
			"kind": "pooping",
			"duration": 13.06,
			"img": ".../sdfs.jpg",
			"daynumber": 11,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 0.56,
			"img": ".../sdfs.jpg",
			"daynumber": 12,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 0.45,
			"img": ".../sdfs.jpg",
			"daynumber": 12,
			"day": "sat",
		},
		{
			"kind": "pooping",
			"duration": 19.09,
			"img": ".../sdfs.jpg",
			"daynumber": 12,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 1.10,
			"img": ".../sdfs.jpg",
			"daynumber": 13,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.31,
			"img": ".../sdfs.jpg",
			"daynumber": 13,
			"day": "sun",
		},
		{
			"kind": "pooping",
			"duration": 38.16,
			"img": ".../sdfs.jpg",
			"daynumber": 13,
			"day": "sun",
		},
		{
			"kind": "pooping",
			"duration": 12.48,
			"img": ".../sdfs.jpg",
			"daynumber": 13,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.46,
			"img": ".../sdfs.jpg",
			"daynumber": 14,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.46,
			"img": ".../sdfs.jpg",
			"daynumber": 14,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.50,
			"img": ".../sdfs.jpg",
			"daynumber": 14,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.53,
			"img": ".../sdfs.jpg",
			"daynumber": 15,
			"day": "tue",
		},
		{
			"kind": "pooping",
			"duration": 16.04,
			"img": ".../sdfs.jpg",
			"daynumber": 15,
			"day": "tue",
		},
		{
			"kind": "peeing",
			"duration": 1.11,
			"img": ".../sdfs.jpg",
			"daynumber": 16,
			"day": "wed",
		},
		{
			"kind": "peeing",
			"duration": 0.57,
			"img": ".../sdfs.jpg",
			"daynumber": 16,
			"day": "wed",
		},
		{
			"kind": "pooping",
			"duration": 28.40,
			"img": ".../sdfs.jpg",
			"daynumber": 16,
			"day": "wed",
		}




];