var collection = [


	

		{
			"kind": "peeing",
			"duration": 1.12,
			"img": "day1_0112.png",
			"daynumber": 1,
			"day": "tue",
		},
		{
			"kind": "pooping",
			"duration": 12.29,
			"img": "day1_1229.png",
			"daynumber": 1,
			"day": "tue",
		},
		{
			"kind": "peeing",
			"duration": 1.11,
			"img": "day2_0111.png",
			"daynumber": 2,
			"day": "wed",
		},
		{
			"kind": "pooping",
			"duration": 9.57,
			"img": "day2_0957.png",
			"daynumber": 2,
			"day": "wed",
		},	 
		{
			"kind": "peeing",
			"duration": 0.51,
			"img": "day3_0051.png",
			"daynumber": 3,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 0.11,
			"img": "day3_0011.png",
			"daynumber": 3,
			"day": "thu",
		},
		{
			"kind": "pooping",
			"duration": 25.12,
			"img": "day3_2512.png",
			"daynumber": 3,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 1.02,
			"img": "day4_0102.png",
			"daynumber": 4,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 0.46,
			"img": "day4_0046.png",
			"daynumber": 4,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 1.01,
			"img": "day4_0101.png",
			"daynumber": 4,
			"day": "fri",
		},
		{
			"kind": "pooping",
			"duration": 26.28,
			"img": "day4_2628.png",
			"daynumber": 4,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 0.56,
			"img": "day5_0056.png",
			"daynumber": 5,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 0.48,
			"img": "day5_0048.png",
			"daynumber": 5,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 0.35,
			"img": "day6_0035.png",
			"daynumber": 6,
			"day": "sun",
		},
		{
			"kind": "pooping",
			"duration": 13.44,
			"img": "day6_1344.png",
			"daynumber": 6,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 1.05,
			"img": "day6_0105.png",
			"daynumber": 6,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.41,
			"img": "day7_0041.png",
			"daynumber": 7,
			"day": "mon",
		},
		{
			"kind": "pooping",
			"duration": 18.56,
			"img": "day7_1856.png",
			"daynumber": 7,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.45,
			"img": "day7_0045.png",
			"daynumber": 7,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.44,
			"img": "day8_0044.png",
			"daynumber": 8,
			"day": "tue",
		},
		{
			"kind": "pooping",
			"duration": 30.00,
			"img": "day8_3000.png",
			"daynumber": 8,
			"day": "tue",
		},
		{
			"kind": "peeing",
			"duration": 0.35,
			"img": "day9_0035.png",
			"daynumber": 9,
			"day": "wed",
		},
		{
			"kind": "peeing",
			"duration": 1.07,
			"img": "day10_0107.png",
			"daynumber": 10,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 0.51,
			"img": "day10_0051.png",
			"daynumber": 10,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 1.05,
			"img": "day11_0105.png",
			"daynumber": 11,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 0.53,
			"img": "day11_0053.png",
			"daynumber": 11,
			"day": "fri",
		},
		{
			"kind": "pooping",
			"duration": 13.56,
			"img": "day11_1356.png",
			"daynumber": 11,
			"day": "fri",
		},
		{
			"kind": "pooping",
			"duration": 13.06,
			"img": "day11_1306.png",
			"daynumber": 11,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 0.56,
			"img": "day12_0056.png",
			"daynumber": 12,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 0.45,
			"img": "day12_0045.png",
			"daynumber": 12,
			"day": "sat",
		},
		{
			"kind": "pooping",
			"duration": 19.09,
			"img": "day12_1909.png",
			"daynumber": 12,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 1.10,
			"img": "day13_0110.png",
			"daynumber": 13,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.31,
			"img": "day13_0031.png",
			"daynumber": 13,
			"day": "sun",
		},
		{
			"kind": "pooping",
			"duration": 38.16,
			"img": "day13_3816.png",
			"daynumber": 13,
			"day": "sun",
		},
		{
			"kind": "pooping",
			"duration": 12.48,
			"img": "day13_1248.png",
			"daynumber": 13,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.46,
			"img": "day14_0046.png",
			"daynumber": 14,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.46,
			"img": "day14_0046a.png",
			"daynumber": 14,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.50,
			"img": "day14_0050.png",
			"daynumber": 14,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 0.53,
			"img": "day15_0053.png",
			"daynumber": 15,
			"day": "tue",
		},
		{
			"kind": "pooping",
			"duration": 16.04,
			"img": "day15_1604.png",
			"daynumber": 15,
			"day": "tue",
		},
		{
			"kind": "peeing",
			"duration": 1.11,
			"img": "day16_0111.png",
			"daynumber": 16,
			"day": "wed",
		},
		{
			"kind": "peeing",
			"duration": 0.57,
			"img": "day16_0057.png",
			"daynumber": 16,
			"day": "wed",
		},
		{
			"kind": "pooping",
			"duration": 28.40,
			"img": "day16_2804.png",
			"daynumber": 16,
			"day": "wed",
		},
		{
			"kind": "peeing",
			"duration": 1.05,
			"img": "day17_0105.png",
			"daynumber": 17,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 0.52,
			"img": "day17_0052.png",
			"daynumber": 17,
			"day": "thu",
		},
		{
			"kind": "pooping",
			"duration": 7.27,
			"img": "day17_0727.png",
			"daynumber": 17,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 0.44,
			"img": "day18_0044.png",
			"daynumber": 18,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 0.44,
			"img": "day18_0044a.png",
			"daynumber": 18,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 1.06,
			"img": "day19_0106.png",
			"daynumber": 19,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 1.39,
			"img": "day19_0139.png",
			"daynumber": 19,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 0.26,
			"img": "day19_0026.png",
			"daynumber": 19,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 0.43,
			"img": "day19_0043.png",
			"daynumber": 19,
			"day": "sat",
		},
		{
			"kind": "pooping",
			"duration": 20.34,
			"img": "day19_2034.png",
			"daynumber": 19,
			"day": "sat",
		},
		{
			"kind": "peeing",
			"duration": 0.34,
			"img": "day20_0034.png",
			"daynumber": 20,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.57,
			"img": "day20_0057.png",
			"daynumber": 20,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.55,
			"img": "day20_0055.png",
			"daynumber": 20,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.56,
			"img": "day20_0056.png",
			"daynumber": 20,
			"day": "sun",
		},
		{
			"kind": "peeing",
			"duration": 0.37,
			"img": "day21_0037.png",
			"daynumber": 21,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 1.04,
			"img": "day21_0104.png",
			"daynumber": 21,
			"day": "mon",
		},
		{
			"kind": "pooping",
			"duration": 15.56,
			"img": "day21_1556.png",
			"daynumber": 21,
			"day": "mon",
		},
		{
			"kind": "peeing",
			"duration": 1.02,
			"img": "day22_0102.png",
			"daynumber": 22,
			"day": "tue",
		},
		{
			"kind": "peeing",
			"duration": 0.54,
			"img": "day22_0054.png",
			"daynumber": 22,
			"day": "tue",
		},
		{
			"kind": "peeing",
			"duration": 0.48,
			"img": "day23_0048.png",
			"daynumber": 23,
			"day": "wed",
		},
		{
			"kind": "peeing",
			"duration": 1.08,
			"img": "day23_0108.png",
			"daynumber": 23,
			"day": "wed",
		},
		{
			"kind": "pooping",
			"duration": 28.38,
			"img": "day23_2838.png",
			"daynumber": 23,
			"day": "wed",
		},
		{
			"kind": "peeing",
			"duration": 0.53,
			"img": "day23_0053.png",
			"daynumber": 23,
			"day": "wed",
		},
		{
			"kind": "pooping",
			"duration": 12.29,
			"img": "day24_1229.png",
			"daynumber": 24,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 1.16,
			"img": "day24_0116.png",
			"daynumber": 24,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 0.42,
			"img": "day24_0042.png",
			"daynumber": 24,
			"day": "thu",
		},
		{
			"kind": "peeing",
			"duration": 0.16,
			"img": "day25_0016.png",
			"daynumber": 25,
			"day": "fri",
		},
		{
			"kind": "peeing",
			"duration": 1.05,
			"img": "day25_0105.png",
			"daynumber": 25,
			"day": "fri",
		},
		{
			"kind": "pooping",
			"duration": 19.03,
			"img": "day25_1903.png",
			"daynumber": 25,
			"day": "fri",
		}







];